// src/components/Checkbox.tsx
import { type Dispatch, type JSX, type ReactNode, type SetStateAction } from "react";

export default function Checkbox({
    children: legend,
    name,
    id = name,
    column = false,
    className,
    state,
    setState
}: CheckboxProps): JSX.Element {
    return (
        <div className={className}>
            <label htmlFor={id} className={`flex w-fit gap-2 cursor-pointer ${column ? "flex-col" : "flex-row items-center"}`}>
                <div className="group border-2 border-neutral-300 w-4 h-4 flex justify-center items-center">
                    <i className="bi bi-check text-blue-500 text-lg scale-0 group-has-checked:scale-100 duration-100"></i>
                    <input type="checkbox" name={name} id={id} className="hidden" checked={state} onChange={(e) => setState(e.currentTarget.checked)} />
                </div>
                <h4 className="flex">{legend}</h4>
            </label>
        </div>
    );
}

interface CheckboxProps {
    id?: string;
    className?: string;
    children: ReactNode;
    name: string;
    column?: boolean;
    state: boolean;
    setState: Dispatch<SetStateAction<boolean>>;
}

// src/lib/components/Checkbox.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    interface CheckboxProps {
        id: string;
        name?: string;
        children?: Snippet;
        class?: string;
        checked: boolean;
    }

    let { 
        children,
        id,
        name = id,
        class: className,
        checked = $bindable()
    }: CheckboxProps = $props();
</script>

<div class={className}>
    <label for={id} class="flex w-fit gap-2 cursor-pointer items-center">
        <div class="group border border-neutral-300 size-4 flex justify-center items-center">
            <i class="bi bi-check scale-0 group-has-checked:scale-100 duration-100"></i>
            <input type="checkbox" {name} {id} class="hidden" bind:checked={checked} />
        </div>
        <h4 class="flex">{@render children?.()}</h4>
    </label>
</div>
